version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '5555:5555'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=duck
      - POSTGRES_PASSWORD=ResTres